# Generated by Django 5.2 on 2025-04-25 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the indicator (e.g. 'Interest Rate')", max_length=100)),
                ('country', models.CharField(help_text='Country or region the indicator belongs to', max_length=100)),
                ('value', models.DecimalField(decimal_places=4, help_text='Current value of the indicator', max_digits=12)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, help_text='Previous value of the indicator', max_digits=12, null=True)),
                ('unit', models.CharField(help_text="Unit of measurement (e.g. '%', 'USD', 'Points')", max_length=50)),
                ('frequency', models.CharField(help_text="Update frequency (e.g. 'Daily', 'Monthly', 'Quarterly')", max_length=50)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the indicator was updated')),
                ('source', models.CharField(default='Trading Economics', help_text='Source of the indicator data', max_length=100)),
                ('category', models.CharField(help_text="Category of the indicator (e.g. 'Monetary', 'Economic Growth', 'Trade')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what the indicator measures')),
            ],
            options={
                'ordering': ['-last_update'],
                'indexes': [models.Index(fields=['country', 'name'], name='indicators__country_9fbc4f_idx'), models.Index(fields=['category'], name='indicators__categor_ada8a8_idx'), models.Index(fields=['last_update'], name='indicators__last_up_97dbde_idx')],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
